name: Dev

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - "16"
          - "14"
        include:
          # only enable coverage on the fastest job
          - node: "16"
            ENABLE_CODE_COVERAGE: true

    env:
      NODE_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Setup python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install pynvim

      - name: Setup vim
        uses: rhysd/action-setup-vim@v1.2.13
        id: vim
        with:
          version: v8.2.0750

      - name: Setup neovim
        id: nvim
        uses: rhysd/action-setup-vim@v1.2.13
        with:
          neovim: true

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile
          sudo apt-get install -y xclip ripgrep exuberant-ctags
          xclip -version
          rg --version
          ctags --version

      - name: Run jest
        env:
          VIM_COMMAND: ${{ steps.vim.outputs.executable }}
          NVIM_COMMAND: ${{ steps.nvim.outputs.executable }}
        run: |
          export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-linux64/bin"
          vim --version
          nvim --version
          echo $VIM_COMMAND
          echo $NVIM_COMMAND
          node --max-old-space-size=4096 --expose-gc ./node_modules/.bin/jest --maxWorkers=2 --coverage --forceExit

      - name: Codecov
        uses: codecov/codecov-action@v1
        if: ${{ matrix.ENABLE_CODE_COVERAGE }}
        with:
          fail_ci_if_error: true
